# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxMoyaExample' do
  use_frameworks!

  pod 'RxCocoa', '~> 3.0.0'
  pod 'Moya-ModelMapper/RxSwift', '~> 4.1.0'
  pod 'RxOptional'

  # Pods for RxMoyaExample

  target 'RxMoyaExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxMoyaExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
